x-ollama-model: &ollama-model "llama3.1"

services:
  db:
    image: postgres
    container_name: mcpg_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username postgres"]
      interval: 5s
      timeout: 2s
      retries: 10

  server:
    image: golang
    container_name: mcpg_server
    volumes:
      - ../:/app
    working_dir: /app
    environment:
      DB_URL: "postgres://postgres@db:5432/postgres"
    command:
      - sh
      - -c
      - go run .
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/mcp/health"]
      interval: 5s
      timeout: 2s
      retries: 10
    depends_on:
      db:
        condition: service_healthy

  ollama:
    image: ollama/ollama
    container_name: mcpg_ollama
    # NOTE : uncomment to use Nvidia GPUs. I'm using Apple GPUs
    # gpus: all
    volumes:
      - ./ollama_data:/root/.ollama
    healthcheck:
      # The ollama image doesn't include curl, wget or nc, so we use perl
      test: ["CMD-SHELL", "perl -e 'use IO::Socket::INET; IO::Socket::INET->new(\"localhost:11434\") or exit 1;'"]
      interval: 5s
      timeout: 2s
      retries: 10
  ollama-init:
    image: ollama/ollama
    container_name: mcpg_ollama-init
    environment:
      OLLAMA_HOST: "http://ollama:11434"
    depends_on:
      ollama:
        condition: service_healthy
        restart: true
    command: ["pull", *ollama-model]

  app:
    image: python
    container_name: mcpg_python_app
    volumes:
      - ./app:/app
    working_dir: /app
    command:
      - sh
      - -c
      - pip install --upgrade pip && pip install -r requirements.txt && python app.py
    environment:
      OPENAI_BASE_URL: "http://ollama:11434/v1"
      MCP_HOST: "http://server:8080/mcp"
      MODEL: *ollama-model
    depends_on:
      # NOTE : This works with docker, but not with version 5.5.2 of podman.
      # With podman, I get this error :
      # [app]         | Error: unable to start container <app container ID>: preparing container <app container ID> for attach: generating dependency graph for container <app container ID>: container <ollama-init container ID> depends on container <ollama container ID> not found in input list: no such container
      # It seems the issue is known, fixed, but not yet released : https://github.com/containers/podman-compose/issues/1265
      ollama-init:
        condition: service_completed_successfully
      server:
        # FIXME : We should wait to the MCP server to be up an running (condition: service_healthy).
        # However, the /mcp/health endpoint doesn't seem to exist even though it is documented :
        # https://mcp-go.dev/transports/http/#standard-mcp-endpoints
        # So, for now, we'll just check that the server container is started.
        # Luckily, that works but it's not ideal
        condition: service_started
